version: '3'
services:
  web:
    build: .
    platform: linux/amd64
    ports:
      - 3015:3015
    volumes:
      - .:/var/www/rails-ansible-presentation
    env_file:
      .env.docker
    command: /bin/sh -c "rm -f /var/www/core/tmp/pids/server.pid && rails s -b 0.0.0.0"
