---
- name: Create Ec2 instances
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Launch ec2 instances
      tags: create_ec2
      amazon.aws.ec2_instance:
        name: "{{ aws_tag_name }}"
        region: "{{ aws_region }}"
        key_name: "{{ aws_key_name }}"
        instance_type: "{{ aws_instance_type }}"
        image_id: "{{ aws_image }}"
        wait: yes
        wait_timeout: 500
        count: "{{ aws_count }}"
        security_group: "{{ aws_security_group }}"
        vpc_subnet_id: "{{ aws_vpc_subnet }}"
        network:
          assign_public_ip: true
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        user_data: |
          #!/bin/bash
          item=1
          apt-get update
          apt-get install python3.8 -y
